# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='kod_gminy',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
