# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_vote_kod_gminy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gmina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Powiat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wojewodztwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='vote',
            name='kod_gminy',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='okreg',
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Candidate'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='gmina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Gmina'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='powiat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Powiat'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='wojewodztwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Wojewodztwo'),
        ),
        migrations.AddField(
            model_name='powiat',
            name='wojewodztwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Wojewodztwo'),
        ),
        migrations.AddField(
            model_name='gmina',
            name='powiat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Powiat'),
        ),
    ]
