# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-19 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_auto_20170319_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='turnout',
        ),
        migrations.RemoveField(
            model_name='gmina',
            name='turnout',
        ),
        migrations.RemoveField(
            model_name='powiat',
            name='turnout',
        ),
        migrations.RemoveField(
            model_name='wojewodztwo',
            name='turnout',
        ),
        migrations.AddField(
            model_name='gmina',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='powiat',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wojewodztwo',
            name='population',
            field=models.IntegerField(default=0),
        ),
    ]
