# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-19 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_auto_20170319_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gmina',
            old_name='population',
            new_name='ballots',
        ),
        migrations.RenameField(
            model_name='powiat',
            old_name='population',
            new_name='ballots',
        ),
        migrations.RenameField(
            model_name='wojewodztwo',
            old_name='population',
            new_name='ballots',
        ),
        migrations.AddField(
            model_name='gmina',
            name='voters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='powiat',
            name='voters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wojewodztwo',
            name='voters',
            field=models.IntegerField(default=0),
        ),
    ]
