# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-24 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_auto_20170319_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmina',
            name='slug',
            field=models.CharField(default='sdf', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powiat',
            name='slug',
            field=models.CharField(default='dfdf', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wojewodztwo',
            name='slug',
            field=models.CharField(default='sdfd', max_length=200),
            preserve_default=False,
        ),
    ]
