# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_auto_20170324_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('voters', models.IntegerField(default=0)),
                ('ballots', models.IntegerField(default=0)),
                ('slug', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='gmina',
            name='ballots',
        ),
        migrations.RemoveField(
            model_name='gmina',
            name='code',
        ),
        migrations.RemoveField(
            model_name='gmina',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gmina',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='gmina',
            name='voters',
        ),
        migrations.RemoveField(
            model_name='powiat',
            name='ballots',
        ),
        migrations.RemoveField(
            model_name='powiat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='powiat',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='powiat',
            name='voters',
        ),
        migrations.RemoveField(
            model_name='wojewodztwo',
            name='ballots',
        ),
        migrations.RemoveField(
            model_name='wojewodztwo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='wojewodztwo',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='wojewodztwo',
            name='voters',
        ),
    ]
