# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0008_auto_20170327_0901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.AddField(
            model_name='gmina',
            name='ballots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gmina',
            name='name',
            field=models.CharField(default='df', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gmina',
            name='slug',
            field=models.CharField(default='df', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gmina',
            name='voters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='powiat',
            name='ballots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='powiat',
            name='name',
            field=models.CharField(default='df', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powiat',
            name='slug',
            field=models.CharField(default='df', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powiat',
            name='voters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wojewodztwo',
            name='ballots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wojewodztwo',
            name='name',
            field=models.CharField(default='df', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wojewodztwo',
            name='slug',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wojewodztwo',
            name='voters',
            field=models.IntegerField(default=0),
        ),
    ]
