# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0009_auto_20170327_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmina',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
