# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0010_gmina_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kraj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
