# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0011_kraj'),
    ]

    operations = [
        migrations.AddField(
            model_name='kraj',
            name='ballots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kraj',
            name='name',
            field=models.CharField(default='f', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kraj',
            name='slug',
            field=models.CharField(default='df', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kraj',
            name='voters',
            field=models.IntegerField(default=0),
        ),
    ]
