# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0012_auto_20170327_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kraj',
            name='ballots',
        ),
        migrations.RemoveField(
            model_name='kraj',
            name='voters',
        ),
        migrations.RemoveField(
            model_name='powiat',
            name='ballots',
        ),
        migrations.RemoveField(
            model_name='powiat',
            name='voters',
        ),
        migrations.RemoveField(
            model_name='wojewodztwo',
            name='ballots',
        ),
        migrations.RemoveField(
            model_name='wojewodztwo',
            name='voters',
        ),
    ]
