# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0013_auto_20170422_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='wojewodztwo',
            name='kraj',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='elections.Kraj'),
            preserve_default=False,
        ),
    ]
